### ISSUE TITLE
相同的主板

### ISSUE THREAD

**Issue by SkyGrass** [cloverkits/Ozmosis-GA-H61M-DS2#1]
朋友，我和你一样的主板。你其他什么配件。
我目前装了 BCM94360CS2。但是睡眠秒醒。

**Comment by cloverkits** [comment]
我没有安装无线网卡 显卡是 GTX 650 Clover 配置文件只勾选了 N卡侦测

**Comment by Cloverk1t** [comment]
> 朋友，我和你一样的主板。你其他什么配件。
> 我目前装了 BCM94360CS2。但是睡眠秒醒。

我没有安装无线网卡 显卡是 GTX 650 Clover 配置文件只勾选了 N卡侦测

**Comment by SkyGrass** [comment]
好吧。关闭 issues 吧

**Comment by Cloverk1t** [comment]
> 好吧。

好吧 睡眠问题在这个主板上应该不存在吧
你使用的 PCI-E 无线网卡还是 USB

**Comment by SkyGrass** [comment]
PCI-E  接到 板子上面的 F-USB 。

**Comment by Cloverk1t** [comment]
> PCI-E 接到 板子上面的 F-USB 。

应该是 USB 问题

**Comment by SkyGrass** [comment]
查了下 说是USB 内建。我按照黑果教程，搞了内建。  貌似没什么用。难道是我内建搞的不对？？ USB2.0 3.0 都正常的。 3.0的速度也 5G了

**Comment by Cloverk1t** [comment]
> 查了下 说是USB 内建。我按照黑果教程，搞了内建。 貌似没什么用。难道是我内建搞的不对？？ USB2.0 3.0 都正常的。 3.0的速度也 5G了

善用搜索 多爬爬贴
