### ISSUE TITLE
同样的主板，可否提供详细配置

### ISSUE THREAD

**Issue by chicitipo** [cloverkits/Ozmosis-GA-H61M-DS2#2]
有台老机器配置技嘉
###############
GA-Z77p-d3
E3 1230 v2
8GB
GTX 560SE
256 SATA SSD
###############
可否使用这个EFI？
显卡需要更换为RX560？570？580？

**Comment by Cloverk1t** [comment]
@chicitipo 我不知道 GTX560SE 在 macOS Mojave 下是否免驱 如果可以的话直接使用我的 EFI 就 OK 了
