### ISSUE TITLE
CPU E3-1230V2 主板GA-Z77P-D3  显卡蓝宝石 RX580

### ISSUE THREAD

**Issue by chezhongkun** [cloverkits/Ozmosis-GA-H61M-DS2#5]
CPU E3-1230V2
主板GA-Z77P-D3
显卡蓝宝石 RX580
DDR3 16G
是否可以直接用这个 EFI 文件

可以直接用【黑果小兵】的镜像文件吗？
macOS Mojave 10.14.6(18G87) Installer for Intel and AMD with Clover 5050 and WEPE

**Comment by Cloverk1t** [comment]
你使用的时候把 Inject EDID 取消勾选 
我注入的是我的显示器 EDID 数据 不通用 我忘记删掉了

**Comment by chezhongkun** [comment]
> 你使用的时候把Inject EDID取消勾选
> 我注入的是我的显示器EDID数据不通用我忘记删掉了
好的
那我是可以直接使用这个【黑锅小兵】的镜像文件去安装 黑苹果了是吧
macOS Mojave 10.14.6(18G87) Installer for Intel and AMD with Clover 5050 and WEPE

**Comment by sg8889** [comment]
使用你的efi一切正常，只是ps2鼠标无法驱动，不知道是什么原因。

**Comment by liaohhhh** [comment]
兄弟你好！我的机器和你的差不多唯一不同的是显卡！我的显卡是蓝宝石6850 2g毒药版。是否能在10.15上使用您的这个EFI。如何使用？或者是在什么系统上直接使用您的这个EFI。。我把你的EFI下载下来在10.13.6-上面使用不成功！

**Comment by Cloverk1t** [comment]
> 兄弟你好！我的机器和你的差不多唯一不同的是显卡！我的显卡是蓝宝石6850 2g毒药版。是否能在10.15上使用您的这个EFI。如何使用？或者是在什么系统上直接使用您的这个EFI。。我把你的EFI下载下来在10.13.6-上面使用不成功！
为什么不用最新版系统呢？ 10.13.6 有点过时了 我没有放对应的驱动
你可以直接把 EFI\CLOVER\kexts\10.15 文件夹里的驱动全部挪到 Other 文件夹
或者复制一份到 10.13 文件夹 然后就能正常使用了

**Comment by liaohhhh** [comment]
我尝试过把10.15的文件驱动全挪到other文件夹！同样的是驱动不成功。。。。。我的机器在10.13.6上面运行驱动都可以安装好！但是在10.15上面我是真都搞不了。。头都晕了！系统我都装了快上百次了！各种都efi也换了！只有10.13.6可以稍微正常点！但是使用10.13.6关机不正常。。。。。。有没有适合我这个配置都系统介绍或者是适合的efi。。。。万分感谢兄弟。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cloverkit"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 晚上8:44
收件人:&nbsp;"cloverkits/GA-Z77P-D3-EFI"<GA-Z77P-D3-EFI@noreply.github.com&gt;;
抄送:&nbsp;"温柔坏男人"<liaohhhh@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cloverkits/GA-Z77P-D3-EFI] CPU E3-1230V2 主板GA-Z77P-D3  显卡蓝宝石 RX580 (#5)



 
兄弟你好！我的机器和你的差不多唯一不同的是显卡！我的显卡是蓝宝石6850 2g毒药版。是否能在10.15上使用您的这个EFI。如何使用？或者是在什么系统上直接使用您的这个EFI。。我把你的EFI下载下来在10.13.6-上面使用不成功！
 为什么不用最新版系统呢？ 10.13.6 有点过时了 我没有放对应的驱动
 你可以直接把 EFI\CLOVER\kexts\10.15 文件夹里的驱动全部挪到 Other 文件夹
 或者复制一份到 10.13 文件夹 然后就能正常使用了

**Comment by Cloverk1t** [comment]
@liaohhhh 如果有条件的话可以自己学着配置 Clover 引导 国内可以多去 PCbeta 看看
