### ISSUE TITLE
使用你的efi一切正常，只是ps2鼠标无法驱动，不知道是什么原因。

### ISSUE THREAD

**Issue by sg8889** [cloverkits/Ozmosis-GA-H61M-DS2#6]

**Comment by Cloverk1t** [comment]
@sg8889 因为我没有加驱动:joy:
最近我入了一把 Filco 忍者圣手二代 87 茶
附送的 USB -> PS/2 转接头 我才发现这个问题
添加 VoodooPS2Controller + VoodooPS2Keyboard 驱动之后解决 同时为了方便还修改了 Function 的映射
不过我还没推送到 GitHub

**Comment by Cloverk1t** [comment]
@cloverkits 对了你是鼠标还需要加入 VoodooPS2Mouse.kext 驱动

**Comment by sg8889** [comment]
拜谢！
