### ISSUE TITLE
GA-Z77-D3H能用吗？

### ISSUE THREAD

**Issue by tjcsr** [cloverkits/Ozmosis-GA-H61M-DS2#7]
CPU  i7-3770K
主板  GA-Z77-D3H
DDR3 8G
这个能安装吗？可以买个RX580

**Comment by Cloverk1t** [comment]
> CPU i7-3770K
> 主板 GA-Z77-D3H
> DDR3 8G
> 这个能安装吗？可以买个RX580

你可以试试看

**Comment by lyf314512** [comment]
和你一样的配置，你成功了吗？efi可以分享下吗
